# Java 捕捉多个异常

> 原文：<https://www.javatpoint.com/multiple-catch-block-in-java>

## Java 多捕获块

一个 try 块后面可以跟一个或多个 catch 块。每个 catch 块必须包含不同的异常处理程序。因此，如果在出现不同的异常时必须执行不同的任务，那么就使用 java multi-catch 块。

## 需要记住的要点

*   一次只发生一个异常，一次只执行一个 catch 块。
*   所有捕获块必须按从最具体到最一般的顺序排列，即算术异常的捕获必须在异常的捕获之前。

### 多抓块流程图

![Java Catch Multiple Exceptions](../img/c27ca3c248cba98906c4839423de417f.png)

### 例 1

让我们看一个简单的 java 多 catch 块的例子。

**MultipleCatchBlock1.java**

```

public class MultipleCatchBlock1 {

	public static void main(String[] args) {

		   try{  
			    int a[]=new int[5];  
			    a[5]=30/0;  
			   }  
			   catch(ArithmeticException e)
		          {
				   System.out.println("Arithmetic Exception occurs");
				  }  
			   catch(ArrayIndexOutOfBoundsException e)
		          {
				   System.out.println("ArrayIndexOutOfBounds Exception occurs");
				  }  
			   catch(Exception e)
		          {
				   System.out.println("Parent Exception occurs");
				  }  		  
			   System.out.println("rest of the code");  
	}
}

```

[Test it Now](https://www.javatpoint.com/opr/test.jsp?filename=MultipleCatchBlock1)

**输出:**

```
Arithmetic Exception occurs
rest of the code

```

### 例 2

**MultipleCatchBlock2.java**

```

public class MultipleCatchBlock2 {

	public static void main(String[] args) {

		   try{  
			    int a[]=new int[5];  

			    System.out.println(a[10]);
			   }  
			   catch(ArithmeticException e)
		          {
				   System.out.println("Arithmetic Exception occurs");
				  }  
			   catch(ArrayIndexOutOfBoundsException e)
		          {
				   System.out.println("ArrayIndexOutOfBounds Exception occurs");
				  }  
			   catch(Exception e)
		          {
				   System.out.println("Parent Exception occurs");
				  }  		  
			   System.out.println("rest of the code");  
	}
}

```

[Test it Now](https://www.javatpoint.com/opr/test.jsp?filename=MultipleCatchBlock2)

**输出:**

```
ArrayIndexOutOfBounds Exception occurs
rest of the code

```

在本例中，try 块包含两个异常。但是一次只发生一个异常，并执行其对应的 catch 块。

**MultipleCatchBlock3.java**

```

public class MultipleCatchBlock3 {

	public static void main(String[] args) {

		   try{  
			    int a[]=new int[5];  
			    a[5]=30/0;  
			    System.out.println(a[10]);
			   }  
			   catch(ArithmeticException e)
		          {
				   System.out.println("Arithmetic Exception occurs");
				  }  
			   catch(ArrayIndexOutOfBoundsException e)
		          {
				   System.out.println("ArrayIndexOutOfBounds Exception occurs");
				  }  
			   catch(Exception e)
		          {
				   System.out.println("Parent Exception occurs");
				  }  		  
			   System.out.println("rest of the code");  
	}
}

```

[Test it Now](https://www.javatpoint.com/opr/test.jsp?filename=MultipleCatchBlock3)

**输出:**

```
Arithmetic Exception occurs
rest of the code

```

### 例 4

在这个例子中，我们生成了 NullPointerException，但是没有提供相应的异常类型。在这种情况下，将调用包含父异常类**异常**的 catch 块。

**MultipleCatchBlock4.java**

```

public class MultipleCatchBlock4 {

	public static void main(String[] args) {

		   try{  
			    String s=null;
			    System.out.println(s.length());
			   }  
			   catch(ArithmeticException e)
		          {
				   System.out.println("Arithmetic Exception occurs");
				  }  
			   catch(ArrayIndexOutOfBoundsException e)
		          {
				   System.out.println("ArrayIndexOutOfBounds Exception occurs");
				  }  
			   catch(Exception e)
		          {
				   System.out.println("Parent Exception occurs");
				  }  		  
			   System.out.println("rest of the code");  
	}
}

```

[Test it Now](https://www.javatpoint.com/opr/test.jsp?filename=MultipleCatchBlock4)

**输出:**

```
Parent Exception occurs
rest of the code

```

### 例 5

让我们看一个例子，在不维护异常顺序的情况下处理异常(即从最具体到最一般)。

**MultipleCatchBlock5.java**

```

class MultipleCatchBlock5{  
  public static void main(String args[]){  
   try{  
    int a[]=new int[5];  
    a[5]=30/0;  
   }  
   catch(Exception e){System.out.println("common task completed");}  
   catch(ArithmeticException e){System.out.println("task1 is completed");}  
   catch(ArrayIndexOutOfBoundsException e){System.out.println("task 2 completed");}  
   System.out.println("rest of the code...");  
 }  
} 

```

[Test it Now](https://www.javatpoint.com/opr/test.jsp?filename=MultipleCatchBlock5)

**输出:**

```
Compile-time error

```

* * *