# Java 异常传播

> 原文：<https://www.javatpoint.com/exception-propagation>

首先从栈顶抛出一个异常，如果没有被捕获，它将沿着调用栈下降到前一个方法。如果没有在那里被捕获，异常将再次下降到前一个方法，以此类推，直到它们被捕获或者到达调用堆栈的最底部。这称为异常传播。

#### 注意:默认情况下，未检查的异常在调用链中转发(传播)。

## 异常传播示例

**test xceptionpaungroup 1 . Java**

```

class TestExceptionPropagation1{
  void m(){
    int data=50/0;
  }
  void n(){
    m();
  }
  void p(){
   try{
    n();
   }catch(Exception e){System.out.println("exception handled");}
  }
  public static void main(String args[]){
   TestExceptionPropagation1 obj=new TestExceptionPropagation1();
   obj.p();
   System.out.println("normal flow...");
  }
}

```

[Test it Now](https://www.javatpoint.com/opr/test.jsp?filename=TestExceptionPropagation1)

**输出:**

```
exception handled
       normal flow...

```

在上面的示例中，异常发生在 m()方法中，在那里它没有被处理，所以它被传播到前面的 n()方法中，在那里它没有被处理，同样，它被传播到处理异常的 p()方法中。

异常可以在调用堆栈中的任何方法中处理，无论是 main()方法、p()方法、n()方法还是 m()方法。

![exception propagation](../img/2b0a5a783fd7e1c2936c7334ff7e380e.png)

#### 注意:默认情况下，选中的异常不会在调用链中转发(传播)。

## 异常传播示例

**test xceptionpaungroup 1 . Java**

```

class TestExceptionPropagation2{
  void m(){
    throw new java.io.IOException("device error");//checked exception
  }
  void n(){
    m();
  }
  void p(){
   try{
    n();
   }catch(Exception e){System.out.println("exception handeled");}
  }
  public static void main(String args[]){
   TestExceptionPropagation2 obj=new TestExceptionPropagation2();
   obj.p();
   System.out.println("normal flow");
  }
}

```

[Test it Now](https://www.javatpoint.com/opr/test.jsp?filename=TestExceptionPropagation2)

**输出:**

```
Compile Time Error

```

* * *