# Java 中`throw`和`throws`的区别

> 原文：<https://www.javatpoint.com/difference-between-throw-and-throws-in-java>

throw 和 throws 是异常处理的概念，其中 `throw`关键字显式地从方法或代码块中抛出异常，而 throws 关键字用于方法的签名中。

[扔](https://www.javatpoint.com/throw-keyword)和[扔](https://www.javatpoint.com/throws-keyword-and-difference-between-throw-and-throws)关键词有很多区别。下面列出了投掷和投掷的区别:

| 不，先生。 | 差异的基础 | 扔 | 投 |
| 1. | 定义 | Java `throw`关键字用于在代码、函数或代码块内部显式抛出异常。 | Java throws 关键字在方法签名中用于声明一个异常，该异常可能在执行代码时被函数抛出。 |
| 2. | 异常的类型使用 `throw`关键字，我们只能传播未检查的异常，即检查的异常不能仅使用 throw 传播。 | 使用 throws 关键字，我们可以声明已检查和未检查的异常。但是，throws 关键字只能用于传播已检查的异常。 |
| 3. | 句法 | `throw`关键字后面跟一个要抛出的 Exception 实例。 | `throws`关键字后面是要抛出的异常的类名。 |
| 4. | 申报 | 方法中使用了 throw。 | throws 与方法签名一起使用。 |
| 5. | 内部实施 | 我们一次只能抛出一个异常，也就是说，我们不能抛出多个异常。 | 我们可以使用方法可以抛出的`throws`关键字来声明多个异常。例如，main()抛出 IOException、SQLException。 |

## Java 抛出示例

**TestThrow.java**

```java

public class TestThrow {
	//defining a method
	public static void checkNum(int num) {
		if (num < 1) {
			throw new ArithmeticException("\nNumber is negative, cannot calculate square");
		}
		else {
			System.out.println("Square of " + num + " is " + (num*num));
		}
	}
	//main method
	public static void main(String[] args) {
			TestThrow obj = new TestThrow();
			obj.checkNum(-3);
			System.out.println("Rest of the code..");
	}
}

```

**输出:**

![Difference between throw and throws in Java](../img/ec6338e658837dcf401f43d1675e9833.png)

## Java 抛出示例

**TestThrows.java**

```java

public class TestThrows {
	//defining a method
	public static int divideNum(int m, int n) throws ArithmeticException {
		int div = m / n;
		return div;
	}
	//main method
	public static void main(String[] args) {
		TestThrows obj = new TestThrows();
		try {
			System.out.println(obj.divideNum(45, 0));
		}
		catch (ArithmeticException e){
			System.out.println("\nNumber cannot be divided by 0");
		}

		System.out.println("Rest of the code..");
	}
}

```

**输出:**

![Difference between throw and throws in Java](../img/3b02856fbbb5981ecc44a5cf64e8462b.png)

## Java `throw`和`throws`示例

**TestThrowAndThrows.java**

```java

public class TestThrowAndThrows
{
    // defining a user-defined method
    // which throws ArithmeticException
    static void method() throws ArithmeticException
    {
        System.out.println("Inside the method()");
        throw new ArithmeticException("throwing ArithmeticException");
    }
    //main method
    public static void main(String args[])
    {
        try
        {
            method();
        }
        catch(ArithmeticException e)
        {
            System.out.println("caught in main() method");
        }
    }
}

```

**输出:**

![Difference between throw and throws in Java](../img/d3ac40abf6a361b49837a62921339fa3.png)

* * *